version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Zipping lambda function...
      - zip -r function.zip lambda/
artifacts:
  files:
    - function.zip
