version: 0.2

env:
  exported-variables:
    - S3_BUCKET_NAME

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - echo "Getting bucket name from SSM..."
      - export S3_BUCKET_NAME=$(aws ssm get-parameter --name "/lambda/artifact/bucket" --query "Parameter.Value" --output text)

  build:
    commands:
      - echo "S3_BUCKET_NAME=$S3_BUCKET_NAME"
      - echo "Zipping Lambda function..."
      - zip -r function.zip lambda/
      - echo "Uploading to S3..."
      - aws s3 cp function.zip s3://$S3_BUCKET_NAME/function.zip

artifacts:
  files:
    - template.yaml  # adjust path if needed
