version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip

  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip function.zip app.py
      - echo "Uploading to S3 bucket..."
      - aws s3 cp function.zip s3://cicd-python-bkt/function.zip --region ap-south-1

artifacts:
  files:
    - function.zip
