version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r function.zip lambda/
      - aws s3 cp function.zip s3://$S3_BUCKET_NAME/function.zip
artifacts:
  files:
    - template.yaml
    - function.zip
